version: "3"
services:
  web-server:
    image: netoviz/web-react
    container_name: nv-web-react
    restart: always
    env_file: .env
    networks:
      - netoviz-nw
    ports:
      # browser access
      - "${NETOVIZ_WEB_PORT}:3000"
    depends_on:
      - proxy-server
      - app-server
  proxy-server:
    image: netoviz/envoy
    container_name: nv-envoy
    restart: always
    networks:
      - netoviz-nw
    env_file: .env
    ports:
      # management (browser access)
      - "${NETOVIZ_PROXY_MGMT_PORT}:9901"
      # grpc-web
      - "${REACT_APP_NETOVIZ_GRPC_WEB_PORT}:8080"
    depends_on:
      - app-server
  app-server:
    image: netoviz/app-server
    container_name: nv-app
    restart: always
    env_file: .env
    volumes:
      - ./storage:/home/netoviz-app-server/db/storage
    networks:
      - netoviz-nw
    ports:
      # REST
      - "${REACT_APP_NETOVIZ_REST_PORT}:3001"
    expose:
      # gRPC
      - "9090"
networks:
  netoviz-nw:
    driver: bridge
